<!--<script type="text/javascript">
    requirejs(['Pulsestorm_JavascriptInitTutorial/example'],function(example){
        alert("Loaded");
        console.log(example);
    });
</script>-->

<!--<div id="one" class="foo">
    Hello World
</div>
<div id="two" class="foo">
    Goodbye World
</div>

<script type="text/x-magento-init">
    {
        ".foo": {
            "Pulsestorm_JavascriptInitTutorial/example":{"config":"value"}
        }
    }
</script>-->

<div data-mage-init='{"Pulsestorm_JavascriptInitTutorial/example": {"another":"example"}}'>A single div</div>